# Using powerlevel9k
ZSH_THEME="powerlevel9k/powerlevel9k"

# If you using powerlevel10k, follow this
# ZSH_THEME="powerlevel10k/powerlevel10k"


# ========== Powerlevel9k config ========== #
# ============= Common 9k, 10k ============ #
POWERLEVEL9K_MODE='nerdfont-complete'
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true

# LEFT, RIGHT PROMPT
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon dir ssh root_indicator vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status time)

# OS Icon
POWERLEVEL9K_OS_ICON_BACKGROUND='235'
POWERLEVEL9K_OS_ICON_FOREGROUND='242'

# Battery
# POWERLEVEL9K_BATTERY_LOW_BACKGROUND='240'
# POWERLEVEL9K_BATTERY_LOW_FOREGROUND='252'
# POWERLEVEL9K_BATTERY_CHARGING_BACKGROUND='240'
# POWERLEVEL9K_BATTERY_CHARGING_FOREGROUND='252'
# POWERLEVEL9K_BATTERY_CHARGED_BACKGROUND='240'
# POWERLEVEL9K_BATTERY_CHARGED_FOREGROUND='252'
# POWERLEVEL9K_BATTERY_DISCONNECTED_BACKGROUND='240'
# POWERLEVEL9K_BATTERY_DISCONNECTED_FOREGROUND='252'

# Time
POWERLEVEL9K_TIME_FORMAT='%D{%I:%M}'
POWERLEVEL9K_TIME_BACKGROUND='234'
POWERLEVEL9K_TIME_FOREGROUND='252'

# Execution time
# POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND='234'
# POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND='246'
# POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=0

# Memory
# POWERLEVEL9K_RAM_ICON=''
# POWERLEVEL9K_RAM_BACKGROUND='none'
# POWERLEVEL9K_RAM_FOREGROUND='006'

# Directory
POWERLEVEL9K_SHORTEN_DELIMITER=''
POWERLEVEL9K_SHORTEN_DIR_LENGTH=7
POWERLEVEL9K_FOLDER_ICON=''
POWERLEVEL9K_DIR_ETC_BACKGROUND='237'
POWERLEVEL9K_DIR_ETC_FOREGROUND='248'
POWERLEVEL9K_DIR_HOME_BACKGROUND='237'
POWERLEVEL9K_DIR_HOME_FOREGROUND='248'
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND='237'
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND='248'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND='237'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND='248'

# Version Control System
POWERLEVEL9K_VCS_CLEAN_BACKGROUND='239'
POWERLEVEL9K_VCS_CLEAN_FOREGROUND='250'
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='239'
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='250'
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='239'
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='250'

# Command result
POWERLEVEL9K_STATUS_OK_BACKGROUND='235'
POWERLEVEL9K_STATUS_OK_FOREGROUND='blue'
POWERLEVEL9K_STATUS_ERROR_BACKGROUND='235'
POWERLEVEL9K_STATUS_ERROR_FOREGROUND='red'
POWERLEVEL9K_STATUS_OK_IN_NON_VERBOSE=true
POWERLEVEL9K_STATUS_VERBOSE=false


# ========== zsh config... ========== #
